// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the generated attribute classes and base types used to decorate user code.
/// </summary>
internal static class AttributesEmitter
{
    /// <summary>
    /// Generates the source code for all marker attributes and the binding context base class.
    /// </summary>
    public static string Emit()
    {
        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{Namespaces.Generated}};

            /// <summary>
            /// Specifies a type whose public members should be bound from command-line arguments.
            /// Apply multiple times to bind multiple types.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
            internal sealed class {{AttributeNames.CommandLineBindableClass}} : global::System.Attribute
            {
                public {{AttributeNames.CommandLineBindableClass}}(global::System.Type type) => Type = type;

                /// <summary>The type to generate binding code for.</summary>
                public global::System.Type Type { get; }
            }

            /// <summary>
            /// Specifies the naming convention used when converting property names to CLI option/argument names.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandLineNamingConventionClass}} : global::System.Attribute
            {
                public {{AttributeNames.CommandLineNamingConventionClass}}(CommandLineNamingConvention convention) => Convention = convention;

                /// <summary>The naming convention to use.</summary>
                public CommandLineNamingConvention Convention { get; }
            }

            /// <summary>
            /// The naming convention for generated CLI names.
            /// </summary>
            internal enum CommandLineNamingConvention
            {
                /// <summary>Convert PascalCase to kebab-case (e.g. "MyOption" → "--my-option"). This is the default.</summary>
                KebabCase = 0,
            }

            /// <summary>
            /// Explicitly marks a property or parameter as a CLI option.
            /// Properties are options by default, so this attribute is optional.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandLineOptionClass}} : global::System.Attribute
            {
                /// <summary>
                /// A type containing a static parser method for this option.
                /// When set, the generator uses the method to convert the raw string token to the target type.
                /// If <see cref="CustomParserMethod"/> is not set, the method must be named <c>Parse</c>.
                /// </summary>
                public global::System.Type? CustomParser { get; set; }

                /// <summary>
                /// The name of the static parser method on <see cref="CustomParser"/>.
                /// Defaults to <c>"Parse"</c> when not specified.
                /// </summary>
                public string? CustomParserMethod { get; set; }
            }

            /// <summary>
            /// Marks a property or parameter as a positional CLI argument.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandLineArgumentClass}} : global::System.Attribute
            {
                /// <summary>
                /// A type containing a static parser method for this argument.
                /// When set, the generator uses the method to convert the raw string token to the target type.
                /// If <see cref="CustomParserMethod"/> is not set, the method must be named <c>Parse</c>.
                /// </summary>
                public global::System.Type? CustomParser { get; set; }

                /// <summary>
                /// The name of the static parser method on <see cref="CustomParser"/>.
                /// Defaults to <c>"Parse"</c> when not specified.
                /// </summary>
                public string? CustomParserMethod { get; set; }
            }

            /// <summary>
            /// Marks a property or parameter to be excluded from command-line binding.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandLineIgnoreClass}} : global::System.Attribute
            {
            }

            /// <summary>
            /// Marks a class as a command handler for hosting with dependency injection.
            /// The generator discovers these classes and generates wiring code.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandLineHandlerClass}} : global::System.Attribute
            {
                public {{AttributeNames.CommandLineHandlerClass}}() { }

                public {{AttributeNames.CommandLineHandlerClass}}(string groupName) => GroupName = groupName;

                /// <summary>The command group name. When set, methods become subcommands of this group.</summary>
                public string GroupName { get; } = "";

                /// <summary>The binding context class that provides Parse and AddOptions methods.</summary>
                public global::System.Type? BindingContext { get; set; }
            }

            /// <summary>
            /// Marks a method as a command handler entry point, optionally with a command name.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class {{AttributeNames.CommandClass}} : global::System.Attribute
            {
                public {{AttributeNames.CommandClass}}(string name = "") => Name = name;

                /// <summary>The command name. Empty string indicates the root command.</summary>
                public string Name { get; }
            }
            """;
    }
}
