// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using StaticCs;

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the generated partial class body for a binding context, including
/// <c>AddOptions&lt;T&gt;</c> extension method and <c>Parse&lt;T&gt;</c> static method.
/// </summary>
internal static class BindingContextEmitter
{
    /// <summary>
    /// Generates the source code for a binding context partial class and its extensions.
    /// </summary>
    public static string Emit(BindingContextInfo context)
    {
        IndentingBuilder builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("using System.CommandLine.Parsing;");
        builder.AppendLine("");

        bool hasNamespace =
            !string.IsNullOrEmpty(context.Namespace) && context.Namespace != Namespaces.Global;

        if (hasNamespace)
        {
            builder.AppendLine($"namespace {context.Namespace};");
            builder.AppendLine("");
        }

        // Generate the partial class with Parse<T> and symbol fields
        builder.AppendLine($"partial class {context.ClassName}");
        builder.AppendLine("{");
        builder.Indent();

        EmitParseMethod(builder, context);

        // Generate internal symbol fields per bindable type
        foreach (BindableTypeInfo type in context.BindableTypes)
        {
            builder.AppendLine("");
            EmitSymbolFields(builder, type);
        }

        builder.Dedent();
        builder.AppendLine("}");

        builder.AppendLine("");

        // Generate the static extensions class with AddOptions<T>
        EmitExtensionsClass(builder, context);

        return builder.ToString();
    }

    private static void EmitParseMethod(IndentingBuilder builder, BindingContextInfo context)
    {
        builder.AppendLine("public static T Parse<T>(ParseResult parseResult)");
        builder.AppendLine("{");
        builder.Indent();

        for (int i = 0; i < context.BindableTypes.Length; i++)
        {
            BindableTypeInfo type = context.BindableTypes[i];
            string prefix = i == 0 ? "if" : "else if";

            builder.AppendLine($"{prefix} (typeof(T) == typeof({type.FullTypeName}))");
            builder.AppendLine("{");
            builder.Indent();
            EmitParseBody(builder, type);
            builder.Dedent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine(
            "throw new InvalidOperationException($\"Type '{typeof(T).FullName}' is not a bindable command-line type.\");"
        );
        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitParseBody(IndentingBuilder builder, BindableTypeInfo type)
    {
        if (type.HasPrimaryConstructor)
        {
            EmitParseBodyForConstructor(builder, type);
        }
        else
        {
            EmitParseBodyForProperties(builder, type);
        }
    }

    private static void EmitParseBodyForConstructor(IndentingBuilder builder, BindableTypeInfo type)
    {
        List<string> ctorArgs = [];
        foreach (MemberInfo member in type.Members)
        {
            string symbolField = GetSymbolFieldName(type, member);
            ctorArgs.Add(FormatGetValue(member, symbolField));
        }

        builder.AppendLine($"return (T)(object)new {type.FullTypeName}(");
        builder.Indent();
        for (int i = 0; i < ctorArgs.Count; i++)
        {
            string suffix = i < ctorArgs.Count - 1 ? "," : ");";
            builder.AppendLine($"{ctorArgs[i]}{suffix}");
        }
        builder.Dedent();
    }

    private static void EmitParseBodyForProperties(IndentingBuilder builder, BindableTypeInfo type)
    {
        builder.AppendLine($"return (T)(object)new {type.FullTypeName}");
        builder.AppendLine("{");
        builder.Indent();
        for (int i = 0; i < type.Members.Length; i++)
        {
            MemberInfo member = type.Members[i];
            string symbolField = GetSymbolFieldName(type, member);
            string value = FormatGetValue(member, symbolField);
            string suffix = i < type.Members.Length - 1 ? "," : "";
            builder.AppendLine($"{member.PropertyName} = {value}{suffix}");
        }
        builder.Dedent();
        builder.AppendLine("};");
    }

    private static string FormatGetValue(MemberInfo member, string symbolField)
    {
        if (member.IsNullable || member.IsBoolean)
        {
            return $"parseResult.GetValue({symbolField})";
        }

        if (member.IsValueType && member.HasDefaultValue)
        {
            return $"parseResult.GetValue({symbolField})";
        }

        if (member.HasDefaultValue)
        {
            return $"parseResult.GetValue({symbolField}) ?? {member.DefaultValue}";
        }

        return $"parseResult.GetValue({symbolField}) ?? throw new InvalidOperationException(\"{(member.IsArgument ? "Argument" : "Option")} '{member.CliName}' was not provided.\")";
    }

    private static void EmitExtensionsClass(IndentingBuilder builder, BindingContextInfo context)
    {
        builder.AppendLine($"internal static class {context.ClassName}Extensions");
        builder.AppendLine("{");
        builder.Indent();

        builder.AppendLine("public static void AddOptions<T>(this Command command)");
        builder.AppendLine("{");
        builder.Indent();

        for (int i = 0; i < context.BindableTypes.Length; i++)
        {
            BindableTypeInfo type = context.BindableTypes[i];
            string prefix = i == 0 ? "if" : "else if";

            builder.AppendLine($"{prefix} (typeof(T) == typeof({type.FullTypeName}))");
            builder.AppendLine("{");
            builder.Indent();

            foreach (MemberInfo member in type.Members)
            {
                string symbolField = $"{context.ClassName}.{GetSymbolFieldName(type, member)}";
                builder.AppendLine($"command.Add({symbolField});");
            }

            builder.Dedent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine(
            "throw new InvalidOperationException($\"Type '{typeof(T).FullName}' is not a bindable command-line type.\");"
        );
        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitSymbolFields(IndentingBuilder builder, BindableTypeInfo type)
    {
        foreach (MemberInfo member in type.Members)
        {
            string fieldName = GetSymbolFieldName(type, member);

            if (member.IsArgument)
            {
                EmitArgumentField(builder, member, fieldName);
            }
            else
            {
                EmitOptionField(builder, member, fieldName);
            }

            builder.AppendLine("");
        }
    }

    private static void EmitArgumentField(
        IndentingBuilder builder,
        MemberInfo member,
        string fieldName
    )
    {
        if (member.HasDefaultValue)
        {
            builder.AppendLine(
                $"internal static readonly Argument<{member.TypeName}> {fieldName} = new Argument<{member.TypeName}>(\"{member.CliName}\") {{ DefaultValueFactory = _ => {member.DefaultValue} }};"
            );
        }
        else
        {
            builder.AppendLine(
                $"internal static readonly Argument<{member.TypeName}> {fieldName} = new Argument<{member.TypeName}>(\"{member.CliName}\");"
            );
        }
    }

    private static void EmitOptionField(
        IndentingBuilder builder,
        MemberInfo member,
        string fieldName
    )
    {
        string optName = $"--{member.CliName}";

        if (member.IsBoolean)
        {
            builder.AppendLine(
                $"internal static readonly Option<bool> {fieldName} = new Option<bool>(\"{optName}\") {{ Arity = ArgumentArity.Zero }};"
            );
        }
        else if (member.HasDefaultValue)
        {
            builder.AppendLine(
                $"internal static readonly Option<{member.TypeName}> {fieldName} = new Option<{member.TypeName}>(\"{optName}\") {{ DefaultValueFactory = _ => {member.DefaultValue} }};"
            );
        }
        else
        {
            builder.AppendLine(
                $"internal static readonly Option<{member.TypeName}> {fieldName} = new Option<{member.TypeName}>(\"{optName}\"){((!member.IsNullable) ? " { Required = true }" : "")};"
            );
        }
    }

    private static string GetSymbolFieldName(BindableTypeInfo type, MemberInfo member)
    {
        string suffix = member.IsArgument ? "Argument" : "Option";
        return $"s_{type.TypeName}_{member.PropertyName}{suffix}";
    }
}
