// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using StaticCs;

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the generated extension class with <c>Add&lt;T&gt;</c> method and
/// action classes for DI-based command handler wiring.
/// </summary>
internal static class CommandHandlerEmitter
{
    /// <summary>
    /// Generates the source code for handler wiring (Add&lt;T&gt; and action classes).
    /// </summary>
    public static string Emit(HandlerContextInfo context)
    {
        IndentingBuilder builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("using System.CommandLine.Invocation;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using CommandLineHosting;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("");

        bool hasNamespace =
            !string.IsNullOrEmpty(context.Namespace) && context.Namespace != Namespaces.Global;

        if (hasNamespace)
        {
            builder.AppendLine($"namespace {context.Namespace};");
            builder.AppendLine("");
        }

        string contextRef = hasNamespace ? context.ClassName : $"global::{context.ClassName}";

        builder.AppendLine($"internal static class {context.ClassName}HandlerExtensions");
        builder.AppendLine("{");
        builder.Indent();

        EmitAddMethod(builder, context, contextRef);

        // Emit action classes for each handler's methods
        foreach (CommandHandlerInfo handler in context.Handlers)
        {
            foreach (CommandMethodInfo cmd in handler.Commands)
            {
                builder.AppendLine("");
                EmitActionClass(builder, handler, cmd, contextRef);
            }
        }

        builder.Dedent();
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitAddMethod(
        IndentingBuilder builder,
        HandlerContextInfo context,
        string contextRef
    )
    {
        builder.AppendLine("public static void Add<T>(this CommandLineApplicationBuilder builder)");
        builder.AppendLine("{");
        builder.Indent();

        for (int i = 0; i < context.Handlers.Length; i++)
        {
            CommandHandlerInfo handler = context.Handlers[i];
            string prefix = i == 0 ? "if" : "else if";

            builder.AppendLine($"{prefix} (typeof(T) == typeof({handler.FullTypeName}))");
            builder.AppendLine("{");
            builder.Indent();

            builder.AppendLine($"builder.Services.AddSingleton<{handler.FullTypeName}>();");

            if (string.IsNullOrEmpty(handler.GroupName))
            {
                EmitUngroupedHandler(builder, handler);
            }
            else
            {
                EmitGroupedHandler(builder, handler);
            }

            builder.Dedent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine(
            "throw new InvalidOperationException($\"No command found for type {typeof(T).FullName}\");"
        );
        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }

    /// <summary>
    /// Emits wiring for a handler with no group name — single root command.
    /// </summary>
    private static void EmitUngroupedHandler(IndentingBuilder builder, CommandHandlerInfo handler)
    {
        // Should have exactly one command method
        CommandMethodInfo cmd = handler.Commands[0];
        string actionClassName = GetActionClassName(handler, cmd);

        builder.AppendLine("RootCommand rootCommand = new RootCommand();");
        if (cmd.OptionsFullTypeName is not null)
        {
            builder.AppendLine($"rootCommand.AddOptions<{cmd.OptionsFullTypeName}>();");
        }
        builder.AppendLine($"rootCommand.Action = new {actionClassName}();");
        builder.AppendLine("builder.AddRootCommand(rootCommand);");
    }

    /// <summary>
    /// Emits wiring for a handler with a group name — named command with subcommands.
    /// </summary>
    private static void EmitGroupedHandler(IndentingBuilder builder, CommandHandlerInfo handler)
    {
        string groupVar = "groupCommand";
        builder.AppendLine($"Command {groupVar} = new Command(\"{handler.GroupName}\");");

        foreach (CommandMethodInfo cmd in handler.Commands)
        {
            string actionClassName = GetActionClassName(handler, cmd);

            if (string.IsNullOrEmpty(cmd.CommandName))
            {
                // [Command] with no name — action on the group command itself
                if (cmd.OptionsFullTypeName is not null)
                {
                    builder.AppendLine($"{groupVar}.AddOptions<{cmd.OptionsFullTypeName}>();");
                }
                builder.AppendLine($"{groupVar}.Action = new {actionClassName}();");
            }
            else
            {
                // [Command("name")] — subcommand
                string subVar = $"{cmd.CommandName}Command";
                builder.AppendLine($"Command {subVar} = new Command(\"{cmd.CommandName}\");");
                if (cmd.OptionsFullTypeName is not null)
                {
                    builder.AppendLine($"{subVar}.AddOptions<{cmd.OptionsFullTypeName}>();");
                }
                builder.AppendLine($"{subVar}.Action = new {actionClassName}();");
                builder.AppendLine($"{groupVar}.Add({subVar});");
            }
        }

        builder.AppendLine("RootCommand rootCommand = new RootCommand();");
        builder.AppendLine($"rootCommand.Add({groupVar});");
        builder.AppendLine("builder.AddRootCommand(rootCommand);");
    }

    private static void EmitActionClass(
        IndentingBuilder builder,
        CommandHandlerInfo handler,
        CommandMethodInfo cmd,
        string contextRef
    )
    {
        string actionClassName = GetActionClassName(handler, cmd);

        builder.AppendLine(
            $"private sealed class {actionClassName} : AsynchronousCommandLineAction"
        );
        builder.AppendLine("{");
        builder.Indent();

        // InvokeAsync method
        if (cmd.IsAsync)
        {
            builder.AppendLine(
                "public override async Task<int> InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken = default)"
            );
        }
        else
        {
            builder.AppendLine(
                "public override Task<int> InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken = default)"
            );
        }
        builder.AppendLine("{");
        builder.Indent();

        // Resolve service provider and command instance
        builder.AppendLine(
            "CommandLineHostConfiguration config = (CommandLineHostConfiguration)parseResult.InvocationConfiguration;"
        );
        builder.AppendLine(
            $"{handler.FullTypeName} command = config.ServiceProvider.GetRequiredService<{handler.FullTypeName}>();"
        );

        // Parse options if the method takes a parameter
        bool hasOptions = cmd.OptionsFullTypeName is not null;
        if (hasOptions)
        {
            builder.AppendLine(
                $"{cmd.OptionsFullTypeName} options = {contextRef}.Parse<{cmd.OptionsFullTypeName}>(parseResult);"
            );
        }

        // Build method call arguments
        string optionsArg = hasOptions ? "options" : "";
        string ctArg = cmd.AcceptsCancellationToken
            ? (hasOptions ? ", cancellationToken" : "cancellationToken")
            : "";
        string args = $"{optionsArg}{ctArg}";

        // Invoke the handler method based on return type
        if (cmd.IsAsync && cmd.ReturnsExitCode)
        {
            builder.AppendLine(
                $"return await command.{cmd.MethodName}({args}).ConfigureAwait(false);"
            );
        }
        else if (cmd.IsAsync)
        {
            builder.AppendLine($"await command.{cmd.MethodName}({args}).ConfigureAwait(false);");
            builder.AppendLine("return 0;");
        }
        else if (cmd.ReturnsExitCode)
        {
            builder.AppendLine($"return Task.FromResult(command.{cmd.MethodName}({args}));");
        }
        else
        {
            builder.AppendLine($"command.{cmd.MethodName}({args});");
            builder.AppendLine("return Task.FromResult(0);");
        }

        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static string GetActionClassName(CommandHandlerInfo handler, CommandMethodInfo cmd)
    {
        return $"{handler.TypeName}{cmd.MethodName}Action";
    }
}
