// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using StaticCs;

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the generated extension class with <c>Add&lt;T&gt;</c> method and
/// action classes for DI-based command handler wiring.
/// </summary>
internal static class CommandHandlerEmitter
{
    /// <summary>
    /// Generates the source code for handler wiring (Add&lt;T&gt; and action classes).
    /// </summary>
    public static string Emit(HandlerContextInfo context)
    {
        IndentingBuilder builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("using System.CommandLine.Invocation;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using CommandLineHosting;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("");

        bool hasNamespace =
            !string.IsNullOrEmpty(context.Namespace) && context.Namespace != Namespaces.Global;

        if (hasNamespace)
        {
            builder.AppendLine($"namespace {context.Namespace};");
            builder.AppendLine("");
        }

        string contextRef = hasNamespace ? context.ClassName : $"global::{context.ClassName}";

        builder.AppendLine($"internal static class {context.ClassName}HandlerExtensions");
        builder.AppendLine("{");
        builder.Indent();

        EmitAddMethod(builder, context, contextRef);

        // Emit action classes for each handler
        foreach (CommandHandlerInfo handler in context.Handlers)
        {
            builder.AppendLine("");
            EmitActionClass(builder, handler, contextRef);
        }

        builder.Dedent();
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitAddMethod(
        IndentingBuilder builder,
        HandlerContextInfo context,
        string contextRef
    )
    {
        builder.AppendLine("public static void Add<T>(this CommandLineApplicationBuilder builder)");
        builder.AppendLine("{");
        builder.Indent();

        for (int i = 0; i < context.Handlers.Length; i++)
        {
            CommandHandlerInfo handler = context.Handlers[i];
            string prefix = i == 0 ? "if" : "else if";
            string actionClassName = $"{handler.TypeName}Action";

            builder.AppendLine($"{prefix} (typeof(T) == typeof({handler.FullTypeName}))");
            builder.AppendLine("{");
            builder.Indent();

            builder.AppendLine($"builder.Services.AddSingleton<{handler.FullTypeName}>();");
            builder.AppendLine("RootCommand rootCommand = new RootCommand();");
            builder.AppendLine($"rootCommand.AddOptions<{handler.OptionsFullTypeName}>();");
            builder.AppendLine($"rootCommand.Action = new {actionClassName}();");
            builder.AppendLine("builder.AddRootCommand(rootCommand);");

            builder.Dedent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine(
            "throw new InvalidOperationException($\"No command found for type {typeof(T).FullName}\");"
        );
        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitActionClass(
        IndentingBuilder builder,
        CommandHandlerInfo handler,
        string contextRef
    )
    {
        string actionClassName = $"{handler.TypeName}Action";

        builder.AppendLine(
            $"private sealed class {actionClassName} : AsynchronousCommandLineAction"
        );
        builder.AppendLine("{");
        builder.Indent();

        // InvokeAsync method
        if (handler.IsAsync)
        {
            builder.AppendLine(
                "public override async Task<int> InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken = default)"
            );
        }
        else
        {
            builder.AppendLine(
                "public override Task<int> InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken = default)"
            );
        }
        builder.AppendLine("{");
        builder.Indent();

        // Resolve service provider from InvocationConfiguration
        builder.AppendLine(
            "CommandLineHostConfiguration config = (CommandLineHostConfiguration)parseResult.InvocationConfiguration;"
        );
        builder.AppendLine(
            $"{handler.FullTypeName} command = config.ServiceProvider.GetRequiredService<{handler.FullTypeName}>();"
        );
        builder.AppendLine(
            $"{handler.OptionsFullTypeName} options = {contextRef}.Parse<{handler.OptionsFullTypeName}>(parseResult);"
        );

        // Build method call arguments
        string ctArg = handler.AcceptsCancellationToken ? ", cancellationToken" : "";

        // Invoke the handler method based on return type
        if (handler.IsAsync && handler.ReturnsExitCode)
        {
            builder.AppendLine(
                $"return await command.{handler.MethodName}(options{ctArg}).ConfigureAwait(false);"
            );
        }
        else if (handler.IsAsync)
        {
            builder.AppendLine(
                $"await command.{handler.MethodName}(options{ctArg}).ConfigureAwait(false);"
            );
            builder.AppendLine("return 0;");
        }
        else if (handler.ReturnsExitCode)
        {
            builder.AppendLine(
                $"return Task.FromResult(command.{handler.MethodName}(options{ctArg}));"
            );
        }
        else
        {
            builder.AppendLine($"command.{handler.MethodName}(options{ctArg});");
            builder.AppendLine("return Task.FromResult(0);");
        }

        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");
    }
}
