// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using System.CommandLine;
using System.CommandLine.Invocation;
using CommandLineGenerator;
using CommandLineHosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

HostApplicationBuilder builder = Host.CreateApplicationBuilder();
CommandLineApplicationBuilder commandLineBuilder = builder.WithCommandLine();

commandLineBuilder.Services.AddSingleton<MyService>();
commandLineBuilder.Add<ExampleCommand>();
CommandLineHost commandLineHost = commandLineBuilder.Build(args);
await commandLineHost.RunAsync();

internal sealed record ExampleCommandOptions([CommandLineArgument] string Name);

internal sealed class ExampleCommand(MyService myService)
{
    // Add: [CommandLineHandler("example")]
    public void Execute(ExampleCommandOptions options)
    {
        myService.SayHello(options.Name);
    }
}

internal sealed class MyService
{
    public void SayHello(string name) => Console.WriteLine($"Hello, {name}!");
}

// Add: [CommandLineHandler(typeof(ExampleCommand))]
[CommandLineBindable(typeof(ExampleCommandOptions))]
[CommandLineNamingConvention(CommandLineNamingConvention.KebabCase)]
internal static partial class CommandLineContext { }

#region Generated by CommandLineHandler attribute
internal static class GeneratedCommandLineContextExtensions
{
    public static void Add<T>(this CommandLineApplicationBuilder builder)
    {
        if (typeof(T) == typeof(ExampleCommand))
        {
            builder.Services.AddSingleton<ExampleCommand>();
            RootCommand rootCommand = [];
            rootCommand.AddOptions<ExampleCommandOptions>();
            rootCommand.Action = new ExampleCommandAction();
            builder.AddRootCommand(rootCommand);
        }
        else
        {
            throw new InvalidOperationException($"No command found for type {typeof(T).FullName}");
        }
    }

    internal sealed class ExampleCommandAction : AsynchronousCommandLineAction
    {
        public override Task<int> InvokeAsync(
            ParseResult parseResult,
            CancellationToken cancellationToken = default
        )
        {
            CommandLineHostConfiguration config = (CommandLineHostConfiguration)
                parseResult.InvocationConfiguration;
            ExampleCommand command = config.ServiceProvider.GetRequiredService<ExampleCommand>();
            ExampleCommandOptions options = CommandLineContext.Parse<ExampleCommandOptions>(
                parseResult
            );
            command.Execute(options);
            return Task.FromResult(0);
        }
    }
}

#endregion
